// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as TunnelService from "./tunnelservice.js";
export {
    TunnelService
};

export {
    AutomationPreview,
    AutomationVerdict,
    ConnectionStatus,
    CurrentNetwork,
    DNSLeakResult,
    DNSServer,
    DomainCheck,
    FirewallStatus,
    HelperInfo,
    KnownSSIDs,
    ResolveResult,
    RouteEntry,
    TunnelInfo,
    URLAction,
    UpdateState,
    VerifyRow,
    ZipImportResult
} from "./models.js";
