// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * AutomationPreview is the GUI-facing view of the helper's read-only
 * Automation.Preview: the network the engine currently sees plus one
 * verdict per rule-bearing tunnel. The strings the user reads are built
 * in the frontend from these structured fields (so they go through i18n).
 */
export class AutomationPreview {
    /**
     * Creates a new AutomationPreview instance.
     * @param {Partial<AutomationPreview>} [$$source = {}] - The source object to create the AutomationPreview.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * Available is false when the helper could not be asked (the frontend
             * then hides the strip instead of showing stale or wrong state).
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("ssid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ssid"] = "";
        }
        if (!("ssid_unknown" in $$source)) {
            /**
             * SSIDUnknown is true only when we are online, the primary interface is
             * known to be Wi-Fi, and no SSID is readable (Location Services denied,
             * or a roam blip). An unknown interface (offline, Windows, a utun
             * default route) never counts.
             * @member
             * @type {boolean}
             */
            this["ssid_unknown"] = false;
        }
        if (!("primary_known" in $$source)) {
            /**
             * PrimaryKnown is true when the helper identified the default-route
             * interface; when false, PrimaryIsWiFi is only a placeholder.
             * @member
             * @type {boolean}
             */
            this["primary_known"] = false;
        }
        if (!("primary_is_wifi" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["primary_is_wifi"] = false;
        }
        if (!("online" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["online"] = false;
        }
        if (!("settled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["settled"] = false;
        }
        if (!("settle_remaining_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["settle_remaining_sec"] = 0;
        }
        if (!("has_negated_rules" in $$source)) {
            /**
             * HasNegatedRules is true when any tunnel has an "is not" rule, i.e.
             * the settle window actually holds something back.
             * @member
             * @type {boolean}
             */
            this["has_negated_rules"] = false;
        }
        if (!("tunnels" in $$source)) {
            /**
             * @member
             * @type {AutomationVerdict[]}
             */
            this["tunnels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutomationPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AutomationPreview}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tunnels" in $$parsedSource) {
            $$parsedSource["tunnels"] = $$createField8_0($$parsedSource["tunnels"]);
        }
        return new AutomationPreview(/** @type {Partial<AutomationPreview>} */($$parsedSource));
    }
}

/**
 * AutomationVerdict is one tunnel's evaluated automation state.
 */
export class AutomationVerdict {
    /**
     * Creates a new AutomationVerdict instance.
     * @param {Partial<AutomationVerdict>} [$$source = {}] - The source object to create the AutomationVerdict.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("verdict" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["verdict"] = "";
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * RuleIndex is the 1-based position of the deciding rule (0 = none).
             * @member
             * @type {number | undefined}
             */
            this["rule_index"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * RuleType/RuleNegate/RuleValue describe the deciding rule's condition:
             * type is ssid|subnet|network|none_match, value the SSID/CIDR/MAC.
             * @member
             * @type {string | undefined}
             */
            this["rule_type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["rule_negate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rule_value"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["overlap_cidr"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutomationVerdict instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AutomationVerdict}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AutomationVerdict(/** @type {Partial<AutomationVerdict>} */($$parsedSource));
    }
}

/**
 * ConnectionStatus is re-exported from the domain package so Wails bindings
 * expose the same type that the helper broadcasts — preventing field drift
 * between wire format and frontend expectations.
 */
export const ConnectionStatus = domain$0.ConnectionStatus;

/**
 * ConnectionStatus is re-exported from the domain package so Wails bindings
 * expose the same type that the helper broadcasts — preventing field drift
 * between wire format and frontend expectations.
 * @typedef {domain$0.ConnectionStatus} ConnectionStatus
 */

/**
 * CurrentNetwork is the fingerprint of the network the machine is on now,
 * for the Automation editor's "use current network" button.
 */
export class CurrentNetwork {
    /**
     * Creates a new CurrentNetwork instance.
     * @param {Partial<CurrentNetwork>} [$$source = {}] - The source object to create the CurrentNetwork.
     */
    constructor($$source = {}) {
        if (!("gateway_mac" in $$source)) {
            /**
             * "" when unavailable (e.g. Windows, no gateway)
             * @member
             * @type {string}
             */
            this["gateway_mac"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * human hint, e.g. "192.168.0.0/24"
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CurrentNetwork instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CurrentNetwork}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CurrentNetwork(/** @type {Partial<CurrentNetwork>} */($$parsedSource));
    }
}

/**
 * DNSLeakResult mirrors diag.DNSLeakResult for Wails JSON serialisation.
 */
export class DNSLeakResult {
    /**
     * Creates a new DNSLeakResult instance.
     * @param {Partial<DNSLeakResult>} [$$source = {}] - The source object to create the DNSLeakResult.
     */
    constructor($$source = {}) {
        if (!("leaked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["leaked"] = false;
        }
        if (!("dns_servers" in $$source)) {
            /**
             * @member
             * @type {DNSServer[]}
             */
            this["dns_servers"] = [];
        }
        if (!("test_domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["test_domain"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["split_mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["missing_match_domains"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DomainCheck[] | undefined}
             */
            this["domains"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSLeakResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSLeakResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dns_servers" in $$parsedSource) {
            $$parsedSource["dns_servers"] = $$createField1_0($$parsedSource["dns_servers"]);
        }
        if ("missing_match_domains" in $$parsedSource) {
            $$parsedSource["missing_match_domains"] = $$createField5_0($$parsedSource["missing_match_domains"]);
        }
        if ("domains" in $$parsedSource) {
            $$parsedSource["domains"] = $$createField6_0($$parsedSource["domains"]);
        }
        return new DNSLeakResult(/** @type {Partial<DNSLeakResult>} */($$parsedSource));
    }
}

/**
 * DNSServer mirrors diag.DNSServer.
 */
export class DNSServer {
    /**
     * Creates a new DNSServer instance.
     * @param {Partial<DNSServer>} [$$source = {}] - The source object to create the DNSServer.
     */
    constructor($$source = {}) {
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("is_vpn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_vpn"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSServer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSServer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DNSServer(/** @type {Partial<DNSServer>} */($$parsedSource));
    }
}

/**
 * DomainCheck mirrors diag.DomainCheck.
 */
export class DomainCheck {
    /**
     * Creates a new DomainCheck instance.
     * @param {Partial<DomainCheck>} [$$source = {}] - The source object to create the DomainCheck.
     */
    constructor($$source = {}) {
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["resolver"] = undefined;
        }
        if (!("registered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["registered"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DomainCheck instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DomainCheck}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DomainCheck(/** @type {Partial<DomainCheck>} */($$parsedSource));
    }
}

/**
 * KnownSSIDs is the response shape for GetKnownSSIDs. The frontend uses
 * it to render a picker so users can tap saved networks instead of
 * retyping SSIDs they've already joined.
 */
export class KnownSSIDs {
    /**
     * Creates a new KnownSSIDs instance.
     * @param {Partial<KnownSSIDs>} [$$source = {}] - The source object to create the KnownSSIDs.
     */
    constructor($$source = {}) {
        if (!("current" in $$source)) {
            /**
             * currently-connected SSID (empty if not on Wi-Fi)
             * @member
             * @type {string}
             */
            this["current"] = "";
        }
        if (!("known" in $$source)) {
            /**
             * saved/preferred networks reported by the OS
             * @member
             * @type {string[]}
             */
            this["known"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnownSSIDs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KnownSSIDs}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("known" in $$parsedSource) {
            $$parsedSource["known"] = $$createField1_0($$parsedSource["known"]);
        }
        return new KnownSSIDs(/** @type {Partial<KnownSSIDs>} */($$parsedSource));
    }
}

/**
 * ResolveResult mirrors diag.ResolveResult.
 */
export class ResolveResult {
    /**
     * Creates a new ResolveResult instance.
     * @param {Partial<ResolveResult>} [$$source = {}] - The source object to create the ResolveResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["addrs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["resolver"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["match_domain"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["nxdomain"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["timed_out"] = undefined;
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error_code"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolveResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("addrs" in $$parsedSource) {
            $$parsedSource["addrs"] = $$createField1_0($$parsedSource["addrs"]);
        }
        return new ResolveResult(/** @type {Partial<ResolveResult>} */($$parsedSource));
    }
}

/**
 * RouteEntry mirrors diag.RouteEntry for Wails JSON serialisation.
 */
export class RouteEntry {
    /**
     * Creates a new RouteEntry instance.
     * @param {Partial<RouteEntry>} [$$source = {}] - The source object to create the RouteEntry.
     */
    constructor($$source = {}) {
        if (!("destination" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["destination"] = "";
        }
        if (!("gateway" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gateway"] = "";
        }
        if (!("interface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface"] = "";
        }
        if (!("flags" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["flags"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RouteEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RouteEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RouteEntry(/** @type {Partial<RouteEntry>} */($$parsedSource));
    }
}

/**
 * TunnelInfo is the summary shown in the tunnel list.
 */
export class TunnelInfo {
    /**
     * Creates a new TunnelInfo instance.
     * @param {Partial<TunnelInfo>} [$$source = {}] - The source object to create the TunnelInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("is_connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_connected"] = false;
        }
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["notes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["latency_probe_target"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * CreatedAtUnix is the .conf file's mtime; LastUsedUnix is the most
             * recent connection start from history (0 if never connected). Both
             * feed the tunnel-list "date added" / "last used" sort (issue #17).
             * @member
             * @type {number | undefined}
             */
            this["created_at_unix"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["last_used_unix"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * DNSMode is the intended DNS behaviour from the config: "global"
             * (replaces system DNS), "split" (only DNSDomains) or "none".
             * @member
             * @type {string | undefined}
             */
            this["dns_mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["dns_domains"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelInfo}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dns_domains" in $$parsedSource) {
            $$parsedSource["dns_domains"] = $$createField8_0($$parsedSource["dns_domains"]);
        }
        return new TunnelInfo(/** @type {Partial<TunnelInfo>} */($$parsedSource));
    }
}

/**
 * UpdateState is the frontend-facing snapshot of persisted check state.
 * Exposed so Settings → About can render the "Last checked …" line and
 * the first-check placeholder correctly.
 * 
 * IsDevBuild + AutoEnabled together let the UI distinguish three
 * "not-yet-checked" cases that look identical to a naive `last_check==0`
 * gate:
 * 
 * 	dev build  → scheduler is intentionally inert, show "Never checked"
 * 	auto off   → user disabled the scheduler, show "Never checked"
 * 	auto on    → first tick is 30–120 s away, show "scheduled" hint
 * 
 * CurrentVersion is duplicated here (also in GetVersion()) so the About
 * tab doesn't need two round-trips to render.
 */
export class UpdateState {
    /**
     * Creates a new UpdateState instance.
     * @param {Partial<UpdateState>} [$$source = {}] - The source object to create the UpdateState.
     */
    constructor($$source = {}) {
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (!("last_check_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_check_unix"] = 0;
        }
        if (!("last_seen_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_seen_version"] = "";
        }
        if (!("dismissed_versions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["dismissed_versions"] = [];
        }
        if (!("is_dev_build" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_dev_build"] = false;
        }
        if (!("auto_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_enabled"] = false;
        }
        if (!("last_error_unix" in $$source)) {
            /**
             * LastErrorUnix / ConsecutiveErrors come from update.json: the time of
             * the most recent failed check and how many failed in a row since the
             * last success (0 = healthy). RepoURL is the project the About links
             * and update checks target (a build-time constant: fork builds point
             * at their own repo).
             * @member
             * @type {number}
             */
            this["last_error_unix"] = 0;
        }
        if (!("consecutive_errors" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["consecutive_errors"] = 0;
        }
        if (!("repo_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repo_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateState}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dismissed_versions" in $$parsedSource) {
            $$parsedSource["dismissed_versions"] = $$createField3_0($$parsedSource["dismissed_versions"]);
        }
        return new UpdateState(/** @type {Partial<UpdateState>} */($$parsedSource));
    }
}

/**
 * VerifyRow mirrors diag.VerifyRow for Wails JSON serialisation.
 */
export class VerifyRow {
    /**
     * Creates a new VerifyRow instance.
     * @param {Partial<VerifyRow>} [$$source = {}] - The source object to create the VerifyRow.
     */
    constructor($$source = {}) {
        if (!("check" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["check"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * DetailKey/DetailParams carry a localisable detail (see diag.VerifyRow).
             * @member
             * @type {string | undefined}
             */
            this["detail_key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["detail_params"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hint_key"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VerifyRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VerifyRow}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("detail_params" in $$parsedSource) {
            $$parsedSource["detail_params"] = $$createField4_0($$parsedSource["detail_params"]);
        }
        return new VerifyRow(/** @type {Partial<VerifyRow>} */($$parsedSource));
    }
}

/**
 * ZipImportResult holds the outcome of importing one .conf entry from a zip.
 */
export class ZipImportResult {
    /**
     * Creates a new ZipImportResult instance.
     * @param {Partial<ZipImportResult>} [$$source = {}] - The source object to create the ZipImportResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ZipImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ZipImportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ZipImportResult(/** @type {Partial<ZipImportResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AutomationVerdict.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DNSServer.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = DomainCheck.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
