// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TunnelService is the Wails-bound service.
 * Storage (tunnel files, settings) stays in the GUI process.
 * Tunnel operations go through the helper via an ipc.ClientHolder (so the
 * helper can be re-spawned and the connection swapped without rebuilding
 * the whole service graph).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diag$0 from "../diag/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as healthcheck$0 from "../healthcheck/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ipc$0 from "../ipc/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wifi$0 from "../wifi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutomationBackupRules returns the rules one tunnel had in the named
 * snapshot (validated; no path traversal) without changing anything, so the
 * GUI can register the write it is about to make as its own.
 * @param {string} name
 * @param {string} tunnel
 * @returns {$CancellablePromise<wifi$0.Rule[]>}
 */
export function AutomationBackupRules(name, tunnel) {
    return $Call.ByID(1662492335, name, tunnel).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * BaseName extracts the filename without extension from a path.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function BaseName(path) {
    return $Call.ByID(3469363575, path);
}

/**
 * CheckConflicts loads a tunnel's config and scans local network interfaces
 * for routing overlaps (e.g. Tailscale, another WireGuard instance). Runs
 * entirely in the GUI process — no IPC needed. The frontend calls this before
 * Connect so it can show a warning dialog if conflicts exist.
 * @param {string} name
 * @returns {$CancellablePromise<diag$0.ConflictInfo[]>}
 */
export function CheckConflicts(name) {
    return $Call.ByID(3480969502, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CheckForUpdate is the legacy synchronous check kept for backward
 * compatibility with the (now-removed) onMount call. New code should call
 * ManualCheckForUpdate, which routes through the scheduler so the result
 * is also persisted (ETag, last-checked timestamp) and the in-app banner
 * can update without a separate round-trip.
 * @returns {$CancellablePromise<update$0.UpdateInfo | null>}
 */
export function CheckForUpdate() {
    return $Call.ByID(3781738431).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * CheckSSIDPermission reports whether the process can read the current SSID.
 * Used by the frontend to prompt the user for Location Services access before
 * Wi-Fi auto-connect rules can fire.
 * @returns {$CancellablePromise<wifi$0.SSIDPermissionStatus>}
 */
export function CheckSSIDPermission() {
    return $Call.ByID(2549221651).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ClearConnectionHistory wipes the history file.
 * @returns {$CancellablePromise<void>}
 */
export function ClearConnectionHistory() {
    return $Call.ByID(1952295618);
}

/**
 * CloseHistorySessions closes any open history sessions with the given reason.
 * Called from gui.Run during shutdown so the UI doesn't show phantom "Active"
 * rows after a quit.
 * 
 * Single GetStatus probe — the previous one-IPC-per-session pattern made
 * shutdown latency scale linearly with active tunnel count. The status
 * response carries every active tunnel's rx/tx, so one round-trip is enough.
 * Falls back to the lastKnownStats cache (and ultimately zeros) when the
 * helper is already unreachable. Skipped entirely when no sessions are open
 * (the common quit-while-disconnected case) so shutdown stays snappy.
 * @param {string} reason
 * @returns {$CancellablePromise<void>}
 */
export function CloseHistorySessions(reason) {
    return $Call.ByID(2047156944, reason);
}

/**
 * Connect loads a tunnel config from local storage and asks the helper to
 * bring it up. The helper re-validates server-side.
 * 
 * Session lifecycle is owned entirely by ReconcileHistoryFromStatus —
 * opening here would race the helper's StateConnecting status broadcast,
 * which already includes the tunnel name in ActiveTunnels. The race
 * produced spurious "Reconnected" rows on every user-initiated connect
 * before this was unified.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Connect(name) {
    return $Call.ByID(1123040453, name);
}

/**
 * DeleteTunnel removes a tunnel from local storage. Rejects deletion of the
 * currently connected tunnel (would orphan the interface).
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTunnel(name) {
    return $Call.ByID(3822542112, name);
}

/**
 * Disconnect tears down whatever tunnel the helper currently has active.
 * If the call fails with a "client closed" error (the health monitor may have
 * swapped the client during a recovery), retry once with the fresh client.
 * 
 * We mark lastKnownStats with reason "user" so the upcoming Reconcile (after
 * the next status event with the tunnel gone) labels the closed session as
 * a user disconnect. Existing fresh rx/tx counters from Reconcile's per-tick
 * refresh are preserved — markUserDisconnect overwrites only the reason,
 * not the bytes. This is what protects against rapid double-clicks: the
 * second Disconnect's snapshot may be 0/0 (helper already tearing down)
 * but the cache still holds the fresh values from the steady state.
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(1171530279);
}

/**
 * DisconnectTunnel disconnects a specific tunnel by name. Mirrors
 * Disconnect()'s "client closed" retry: a helper recovery during a
 * per-tunnel disconnect (e.g. user clicks the tray's per-tunnel
 * item right when the health monitor swaps clients) should be
 * transparent, not surfaced as a confusing error.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectTunnel(name) {
    return $Call.ByID(1584259497, name);
}

/**
 * DismissUpdate persists a version dismissal so the in-app banner stays
 * hidden across restarts until a newer version arrives.
 * @param {string} version
 * @returns {$CancellablePromise<void>}
 */
export function DismissUpdate(version) {
    return $Call.ByID(1487086966, version);
}

/**
 * ExportConfig returns the serialized text for display in the export dialog.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExportConfig(name) {
    return $Call.ByID(1684823973, name);
}

/**
 * ExportDiagnostics shows a native save dialog and writes the diagnostics
 * zip (helper log tail, redacted configs, DNS/route/pf state, versions).
 * Private keys are never included. Returns the saved path, or "" if the user
 * cancelled.
 * @returns {$CancellablePromise<string>}
 */
export function ExportDiagnostics() {
    return $Call.ByID(4002171981);
}

/**
 * ExportTunnel shows a native save dialog and writes the .conf file.
 * Returns the saved path, or empty string if the user cancelled.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExportTunnel(name) {
    return $Call.ByID(686002857, name);
}

/**
 * GetAutomationPreview asks the helper for its read-only automation
 * decision (the same data as `wireguide ctl automation`) so the GUI can
 * explain why a tunnel is or is not being connected. On a helper that
 * predates the method, or any IPC failure, it returns Available=false
 * rather than an error so a 2 s poll never spams the UI.
 * @returns {$CancellablePromise<$models.AutomationPreview>}
 */
export function GetAutomationPreview() {
    return $Call.ByID(3585072400).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetConfigText returns the serialized form of a stored tunnel's config.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigText(name) {
    return $Call.ByID(1065418994, name);
}

/**
 * GetConnectionHistory returns recorded sessions newest-first. Always returns
 * a non-nil slice so the frontend doesn't have to special-case "no history
 * yet" vs. "load failed".
 * @returns {$CancellablePromise<storage$0.Session[]>}
 */
export function GetConnectionHistory() {
    return $Call.ByID(3062937901).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetCurrentNetwork returns the current default-gateway MAC fingerprint
 * plus a readable label (the current subnet) so the editor can capture
 * "this network" precisely without the user typing a MAC. GatewayMAC is
 * empty when it can't be determined.
 * @returns {$CancellablePromise<$models.CurrentNetwork>}
 */
export function GetCurrentNetwork() {
    return $Call.ByID(2742143266).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetCurrentSubnets returns the network CIDRs of the physical interfaces
 * the machine is currently on (Wi-Fi or Ethernet). The Automation editor
 * offers these as suggestions for subnet conditions so the user can
 * target the network they're on without knowing its CIDR.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetCurrentSubnets() {
    return $Call.ByID(2824239734).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetFirewallStatus asks the helper for Firewall.Status. It reads pf on
 * macOS, so callers fetch it when Settings opens and on settings changes, not
 * on a timer.
 * @returns {$CancellablePromise<$models.FirewallStatus>}
 */
export function GetFirewallStatus() {
    return $Call.ByID(2324013693).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetHelperInfo describes the running helper. Never an error: the card just
 * shows what it could learn.
 * @returns {$CancellablePromise<$models.HelperInfo>}
 */
export function GetHelperInfo() {
    return $Call.ByID(3946609619).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetKnownSSIDs returns the currently-connected SSID (if any) plus the
 * system's saved wireless networks. Both are best-effort — empty values
 * are normal on a Mac that's only ever been on Ethernet.
 * @returns {$CancellablePromise<$models.KnownSSIDs>}
 */
export function GetKnownSSIDs() {
    return $Call.ByID(57262338).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetLANOverlaps returns the AllowedIPs ranges of a stored tunnel that the
 * macOS connect path will NOT route through the tunnel because they overlap
 * the local network (the same rule as DarwinManager.AddRoutes). Empty on other
 * platforms, which install every range. Read-only; used by the pre-connect
 * "what will change" preview.
 * @param {string} name
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLANOverlaps(name) {
    return $Call.ByID(3276277334, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetLocationAuthorization reports the GUI process's Location Services
 * status: authorized / denied / restricted / not_determined / unknown.
 * Read-only; it never prompts, and the root helper never calls it.
 * @returns {$CancellablePromise<string>}
 */
export function GetLocationAuthorization() {
    return $Call.ByID(3862500133);
}

/**
 * GetRoutingTable returns the current OS routing table.
 * @returns {$CancellablePromise<$models.RouteEntry[]>}
 */
export function GetRoutingTable() {
    return $Call.ByID(3049102509).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @returns {$CancellablePromise<storage$0.Settings | null>}
 */
export function GetSettings() {
    return $Call.ByID(2393200110).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetStatus queries the helper for the current connection status. IPC errors
 * are surfaced to the caller — the frontend needs to distinguish "helper says
 * disconnected" from "helper unreachable".
 * @returns {$CancellablePromise<$models.ConnectionStatus | null>}
 */
export function GetStatus() {
    return $Call.ByID(3544552149).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetTunnelDetail returns the full WireGuardConfig for a tunnel. Used by the
 * detail pane to show allowed IPs, DNS, public keys, etc.
 * @param {string} name
 * @returns {$CancellablePromise<domain$0.WireGuardConfig | null>}
 */
export function GetTunnelDetail(name) {
    return $Call.ByID(3171898132, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GetTunnelHealthCheck returns the tunnel's handshake health-check override:
 * "on", "off" or "inherit" (follow the global setting). Missing or unknown
 * values read as "inherit".
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetTunnelHealthCheck(name) {
    return $Call.ByID(117513249, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<healthcheck$0.Config>}
 */
export function GetTunnelPingHealth(name) {
    return $Call.ByID(3816721483, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * GetUpdateState returns persisted state for the About tab UI.
 * @returns {$CancellablePromise<$models.UpdateState>}
 */
export function GetUpdateState() {
    return $Call.ByID(3155746791).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * GetVersion returns the current app version string.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1775430717);
}

/**
 * ImportConfig parses, validates, and saves a tunnel config under the given
 * name. Returns a TunnelInfo for optimistic UI display.
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function ImportConfig(name, content) {
    return $Call.ByID(2459134310, name, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * ImportQRFromBytes decodes a QR code from raw image bytes (typically supplied
 * by the file picker, which gives us bytes rather than a path) and imports the
 * resulting WireGuard config.
 * @param {string} data
 * @param {string} name
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function ImportQRFromBytes(data, name) {
    return $Call.ByID(3817928306, data, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * ImportQRFromPath reads an image from disk, decodes its QR code, and imports
 * the contained WireGuard config under the given name.
 * @param {string} path
 * @param {string} name
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function ImportQRFromPath(path, name) {
    return $Call.ByID(2544386800, path, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * ImportZip extracts all .conf files from a zip archive and imports each one.
 * Returns per-file results; an error is only returned for zip-level failures.
 * @param {string} path
 * @returns {$CancellablePromise<$models.ZipImportResult[]>}
 */
export function ImportZip(path) {
    return $Call.ByID(976469479, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * ImportZipData imports a zip supplied as raw bytes (used by the file picker,
 * which provides a File object rather than a filesystem path).
 * @param {string} data
 * @returns {$CancellablePromise<$models.ZipImportResult[]>}
 */
export function ImportZipData(data) {
    return $Call.ByID(2432663343, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * LintConfig returns advisory (non-blocking) editor diagnostics for a raw
 * config string: DNS errors mirroring ValidateConfig, plus warnings and hints.
 * It never affects whether a config is valid. Content that does not parse
 * yields no diagnostics (ValidateConfig reports the parse error).
 * @param {string} content
 * @returns {$CancellablePromise<config$0.Diagnostic[]>}
 */
export function LintConfig(content) {
    return $Call.ByID(165708614, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * LintConfigFor is LintConfig for a config being edited under the saved
 * tunnel name `editing` ("" for a new tunnel). That tunnel is excluded from
 * the cross-tunnel duplicate-Address check so an edit never "conflicts" with
 * its own saved copy.
 * @param {string} editing
 * @param {string} content
 * @returns {$CancellablePromise<config$0.Diagnostic[]>}
 */
export function LintConfigFor(editing, content) {
    return $Call.ByID(527601885, editing, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * ListAutomationBackups lists the saved automation snapshots, newest
 * first, counting the rules each holds for tunnel.
 * @param {string} tunnel
 * @returns {$CancellablePromise<storage$0.AutomationBackupInfo[]>}
 */
export function ListAutomationBackups(tunnel) {
    return $Call.ByID(2092962501, tunnel).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * ListTunnels returns every stored tunnel with its summary info.
 * 
 * The active-tunnel marker used to come from an IPC round-trip on every call.
 * That made the tray's rebuild-menu path slow when it was being invoked on
 * the status event stream. The frontend now learns the active tunnel from
 * the status event itself, and the tray caches it internally — so this
 * function stays fully local (disk-only, no IPC) and returns IsConnected
 * purely as a best-effort flag based on a single active-name probe that is
 * safe to skip entirely on slow paths.
 * @returns {$CancellablePromise<$models.TunnelInfo[]>}
 */
export function ListTunnels() {
    return $Call.ByID(3587038916).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * ListTunnelsLocal returns stored tunnels WITHOUT asking the helper which one
 * is active — callers that already know the active name (e.g. the system
 * tray, which tracks it from the status event stream) should use this to
 * avoid an IPC round-trip on every refresh. IsConnected is always false in
 * the returned slice; the caller is responsible for applying its own
 * active-name match.
 * @returns {$CancellablePromise<$models.TunnelInfo[]>}
 */
export function ListTunnelsLocal() {
    return $Call.ByID(3031176175).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * OpenLocationSettings opens System Settings to the Location Services page so
 * the user can grant SSID access without navigating there manually.
 * @returns {$CancellablePromise<void>}
 */
export function OpenLocationSettings() {
    return $Call.ByID(2515541851);
}

/**
 * OpenURL opens a URL in the default browser. Only HTTPS URLs on
 * github.com are allowed to prevent misuse from a compromised frontend.
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(url) {
    return $Call.ByID(1649174774, url);
}

/**
 * ReadFile reads a file from disk (used by native file drop). Returns the
 * content as a string so the frontend can handle name conflicts before import.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(1950850135, path);
}

/**
 * ReconcileHistory is ReconcileHistoryFromStatus with per-tunnel start/end
 * reasons and the SSID at session start. A session's end reason is, in
 * order: the GUI's own "user" hint, the helper's recorded end reason, then
 * DisappearReason ("reconnect" by default).
 * @param {$models.HistoryReconcile} $in
 * @returns {$CancellablePromise<void>}
 */
export function ReconcileHistory($in) {
    return $Call.ByID(2342148573, $in);
}

/**
 * ReconcileHistoryFromStatus is the SINGLE source of truth for opening and
 * closing history sessions. The event bridge calls it on every status event;
 * it diffs the active set against activeSessions and:
 * 
 *   - opens a session for any active tunnel not currently tracked (covers
 *     both user-initiated Connect and helper-driven auto-reconnect / wifi
 *     rules engine / sleep-wake)
 *   - closes a session for any tracked tunnel that has disappeared (using
 *     cached rx/tx + cached reason from lastKnownStats; falls back to
 *     disappearReason — defaults to "reconnect")
 * 
 * Stats cache is always refreshed for currently-active tunnels so disconnect
 * closes have ≤ 1 status-event-tick stale counters. Reason hints set by
 * user-initiated Disconnect / DisconnectTunnel are preserved across cache
 * refreshes — only LoadAndDelete on close clears them.
 * 
 * Fast-path: if the sorted active set hasn't changed since the prior call
 * (the steady-state case at 1 Hz), we skip the activeSessions Range and the
 * open-session loop. The stats cache still gets updated so the eventual
 * disappear-close uses fresh counters.
 * @param {string[]} activeNames
 * @param {{ [_ in string]?: number }} rxByTunnel
 * @param {{ [_ in string]?: number }} txByTunnel
 * @param {string} disappearReason
 * @returns {$CancellablePromise<void>}
 */
export function ReconcileHistoryFromStatus(activeNames, rxByTunnel, txByTunnel, disappearReason) {
    return $Call.ByID(1482043575, activeNames, rxByTunnel, txByTunnel, disappearReason);
}

/**
 * RenameTunnel changes a tunnel's name. Rejects rename of the connected
 * tunnel since the interface name is derived from it.
 * 
 * Routes through the helper's Tunnel.Rename so the active-tunnel check and
 * the file rename both happen under the helper's connectMu — closing the
 * race where a Connect arriving between the GUI's check and the rename
 * could leave the new name in activeCfgs while the file path moved.
 * 
 * Falls back to a direct local rename if the helper rejects the method
 * (older helper that hasn't been upgraded yet).
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameTunnel(oldName, newName) {
    return $Call.ByID(576069505, oldName, newName);
}

/**
 * RepairHelper reinstalls the privileged helper through the administrator
 * repair path. It is the only action here that prompts for a password, and it
 * drops any connected tunnel, so it refuses while one is up.
 * @returns {$CancellablePromise<void>}
 */
export function RepairHelper() {
    return $Call.ByID(2808540712);
}

/**
 * ResetDNS runs Network.ResetDNS. Without force it is refused (Refused in the
 * result, nothing changed) while any tunnel is connected.
 * @param {boolean} force
 * @returns {$CancellablePromise<ipc$0.ResetDNSResponse | null>}
 */
export function ResetDNS(force) {
    return $Call.ByID(1047447379, force).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * ResolveHost resolves name through the system resolver path (getaddrinfo),
 * the same one browsers use, and reports which resolver answered. Unlike
 * dig/nslookup it honours split-DNS supplemental resolvers. Bounded by 3 s.
 * @param {string} name
 * @returns {$CancellablePromise<$models.ResolveResult | null>}
 */
export function ResolveHost(name) {
    return $Call.ByID(3083149897, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * RestoreAutomationBackup replaces tunnel's rules with the ones in the
 * named snapshot. It goes through SaveAutomationRules, so every rule is
 * validated again and the restore is itself snapshotted (and undoable).
 * @param {string} name
 * @param {string} tunnel
 * @returns {$CancellablePromise<void>}
 */
export function RestoreAutomationBackup(name, tunnel) {
    return $Call.ByID(1369266396, name, tunnel);
}

/**
 * RunDNSLeakTest performs a DNS leak test using the currently active tunnel's
 * DNS servers as the expected (VPN) resolvers. If no tunnel is connected, the
 * expected set is empty — all detected resolvers will be flagged as leaks.
 * @returns {$CancellablePromise<$models.DNSLeakResult | null>}
 */
export function RunDNSLeakTest() {
    return $Call.ByID(2469114850).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType39($result);
    }));
}

/**
 * RunUpdate performs the update end-to-end:
 * 
 *   - Homebrew installs → `brew update && brew upgrade --cask wireguide`,
 *     then verifying the installed version and restarting the app.
 *   - Non-brew installs → open the GitHub Releases page in the browser.
 *     Auto-replacing an un-notarised `.app` bundle needs sudo and races
 *     with Gatekeeper quarantining of the new binary; redirecting the
 *     user to the download page is the honest path for an indie macOS
 *     app without an Apple Developer account.
 * @param {update$0.UpdateInfo | null} info
 * @returns {$CancellablePromise<void>}
 */
export function RunUpdate(info) {
    return $Call.ByID(2959589127, info);
}

/**
 * SaveAutomationRules atomically replaces one tunnel's Automation rules.
 * It goes through SettingsStore.Update — the cross-process locked
 * read-modify-write — instead of a whole-object SaveSettings, so a
 * concurrent `wireguide ctl` edit to any other tunnel or field can never
 * be clobbered by a stale GUI snapshot (issue #27 review follow-up).
 * An empty rules slice removes the tunnel's entry entirely. The helper
 * re-reads settings from disk on every evaluation, so no push is needed.
 * @param {string} tunnel
 * @param {wifi$0.Rule[]} rules
 * @returns {$CancellablePromise<void>}
 */
export function SaveAutomationRules(tunnel, rules) {
    return $Call.ByID(657403010, tunnel, rules);
}

/**
 * SaveSettings persists the settings file AND applies any side effects:
 * currently, pushing the new log level to both the GUI's slog handler and
 * the helper's slog handler. Without those side effects a user lowering the
 * level to Debug wouldn't see any new records — the saved file would match
 * the UI but the running process would still be at Info.
 * @param {storage$0.Settings | null} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(3676285513, settings);
}

/**
 * SaveTunnelPingHealth updates only this tunnel's metadata. It cannot overwrite
 * another tunnel's settings, automation rules, notes or WireGuard configuration.
 * @param {string} name
 * @param {healthcheck$0.Config} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveTunnelPingHealth(name, settings) {
    return $Call.ByID(2447701204, name, settings);
}

/**
 * SetApp injects the Wails app for dialog access.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1760917394, app);
}

/**
 * SetDNSProtection asks the helper to lock DNS to the active tunnel's servers.
 * When enabling, we look up the active tunnel's DNS list from local storage
 * and pass it along (the helper never touches user-space storage).
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetDNSProtection(enabled) {
    return $Call.ByID(472068929, enabled);
}

/**
 * SetHealthCheck enables or disables the tunnel health check monitor.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetHealthCheck(enabled) {
    return $Call.ByID(1079240195, enabled);
}

/**
 * SetKillSwitch asks the helper to enable or disable the firewall kill switch.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetKillSwitch(enabled) {
    return $Call.ByID(1469047591, enabled);
}

/**
 * SetLogLevel updates both the GUI's and the helper's slog level
 * immediately. Exposed as a Wails method so the Settings view can call
 * it without waiting for a full SaveSettings round trip.
 * @param {string} level
 * @returns {$CancellablePromise<void>}
 */
export function SetLogLevel(level) {
    return $Call.ByID(537242663, level);
}

/**
 * SetPinInterface enables or disables -ifscope bypass route pinning.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetPinInterface(enabled) {
    return $Call.ByID(1245113173, enabled);
}

/**
 * SetTunnelHealthCheck persists the tunnel's health-check override in its
 * .meta.json sidecar. "inherit" is stored as the absent field, so a tunnel
 * that never overrode the setting keeps a byte-identical sidecar. The helper
 * reads the sidecar on each health-check tick (and receives the value with
 * the next connect), so a change applies without reconnecting where the
 * helper can read the user's files.
 * @param {string} name
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetTunnelHealthCheck(name, value) {
    return $Call.ByID(830677997, name, value);
}

/**
 * SetTunnelLatencyProbeTarget persists the optional per-tunnel ICMP target
 * used only for latency display. The value is deliberately stored outside the
 * WireGuard .conf so exports remain compatible with other clients.
 * @param {string} name
 * @param {string} target
 * @returns {$CancellablePromise<void>}
 */
export function SetTunnelLatencyProbeTarget(name, target) {
    return $Call.ByID(139371444, name, target);
}

/**
 * SetTunnelNotes persists a freeform note for a tunnel. Empty notes still
 * write an empty .meta.json — that matches the contract the frontend
 * expects (write always succeeds, no special-case for "clear").
 * 
 * Existence check first to avoid orphaning a .meta.json sidecar after the
 * .conf was deleted: TunnelDetail's onDestroy can fire-and-forget a
 * pending-edit flush after the user deletes a tunnel, and writing the
 * sidecar in that window would leave a stale file the next tunnel-of-the-
 * same-name would inherit.
 * @param {string} name
 * @param {string} notes
 * @returns {$CancellablePromise<void>}
 */
export function SetTunnelNotes(name, notes) {
    return $Call.ByID(2210192646, name, notes);
}

/**
 * SetUpdateScheduler injects the periodic update-check scheduler and its
 * persistent state store. Called once from gui.Run() after the Wails app
 * is constructed. The frontend's "Check now" / dismiss / last-checked
 * queries route through these.
 * @param {update$0.Scheduler | null} sched
 * @param {update$0.StateStore | null} store
 * @returns {$CancellablePromise<void>}
 */
export function SetUpdateScheduler(sched, store) {
    return $Call.ByID(2970288435, sched, store);
}

/**
 * SplitDNSSupported reports whether connecting a config with ~domain DNS
 * entries can install split DNS on this platform. Windows never can; elsewhere
 * the backend may still fall back at connect time (e.g. Linux without
 * systemd-resolved), which the live status then reports as dns_mode "none".
 * Used by the pre-connect preview.
 * @returns {$CancellablePromise<boolean>}
 */
export function SplitDNSSupported() {
    return $Call.ByID(3977972632);
}

/**
 * TakeURLActions returns (and clears) the URL actions waiting for the user's
 * confirmation. The frontend shows a sheet per action and, on approval,
 * calls the ordinary Connect / DisconnectTunnel methods.
 * @returns {$CancellablePromise<$models.URLAction[]>}
 */
export function TakeURLActions() {
    return $Call.ByID(1243665022).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType41($result);
    }));
}

/**
 * TunnelExists reports whether a tunnel with the given name is stored.
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function TunnelExists(name) {
    return $Call.ByID(1252108931, name);
}

/**
 * UpdateConfig parses, validates, and overwrites an existing tunnel's config.
 * Rejects edits of the connected tunnel.
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConfig(name, content) {
    return $Call.ByID(660046974, name, content);
}

/**
 * ValidateConfig parses and validates a raw config string. Returns a list of
 * human-readable error messages, or nil if the config is valid.
 * @param {string} content
 * @returns {$CancellablePromise<string[]>}
 */
export function ValidateConfig(content) {
    return $Call.ByID(592398029, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * Verify runs the manual post-connect checks for a tunnel: handshake, route
 * per AllowedIPs, split-DNS resolver registration and, when given, a ping of
 * pingHost and a resolve of resolveName. Read-only; every probe is bounded by
 * 3 s. The frontend only calls it on an explicit user click.
 * @param {string} tunnelName
 * @param {string} pingHost
 * @param {string} resolveName
 * @returns {$CancellablePromise<$models.VerifyRow[]>}
 */
export function Verify(tunnelName, pingHost, resolveName) {
    return $Call.ByID(2039407192, tunnelName, pingHost, resolveName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

// Private type creation functions
const $$createType0 = wifi$0.Rule.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = diag$0.ConflictInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = update$0.UpdateInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = wifi$0.SSIDPermissionStatus.createFrom;
const $$createType7 = $models.AutomationPreview.createFrom;
const $$createType8 = storage$0.Session.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.CurrentNetwork.createFrom;
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = $models.FirewallStatus.createFrom;
const $$createType13 = $models.HelperInfo.createFrom;
const $$createType14 = $models.KnownSSIDs.createFrom;
const $$createType15 = $models.RouteEntry.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = storage$0.Settings.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = domain$0.ConnectionStatus.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = domain$0.WireGuardConfig.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = healthcheck$0.Config.createFrom;
const $$createType24 = $models.UpdateState.createFrom;
const $$createType25 = $models.TunnelInfo.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = $models.ZipImportResult.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = config$0.Diagnostic.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = storage$0.AutomationBackupInfo.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = $Create.Array($$createType25);
const $$createType34 = ipc$0.ResetDNSResponse.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = $models.ResolveResult.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = $models.DNSLeakResult.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = $models.URLAction.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = $models.VerifyRow.createFrom;
const $$createType43 = $Create.Array($$createType42);
