// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Diagnostic is one inline editor finding. It is advisory and separate from
 * Validate: a config with only warnings or infos is still valid.
 */
export class Diagnostic {
    /**
     * Creates a new Diagnostic instance.
     * @param {Partial<Diagnostic>} [$$source = {}] - The source object to create the Diagnostic.
     */
    constructor($$source = {}) {
        if (!("field" in $$source)) {
            /**
             * Field is the validator-style location, e.g. "Interface.DNS" or
             * "Peer[0].AllowedIPs". The editor maps it to a line with a key regex.
             * @member
             * @type {string}
             */
            this["field"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("code" in $$source)) {
            /**
             * Code is a stable identifier the frontend uses to look up a translated
             * message ("lint.<code>") with Args; Message is the English fallback.
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["args"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Fix | null | undefined}
             */
            this["fix"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Diagnostic instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Diagnostic}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField4_0($$parsedSource["args"]);
        }
        if ("fix" in $$parsedSource) {
            $$parsedSource["fix"] = $$createField5_0($$parsedSource["fix"]);
        }
        return new Diagnostic(/** @type {Partial<Diagnostic>} */($$parsedSource));
    }
}

/**
 * Fix is an optional one-click remedy attached to a Diagnostic.
 */
export class Fix {
    /**
     * Creates a new Fix instance.
     * @param {Partial<Fix>} [$$source = {}] - The source object to create the Fix.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["value"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Fix instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Fix}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Fix(/** @type {Partial<Fix>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = Fix.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
